// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="t64_nv12toCAG444_k8_t64_nv12toCAG444_k8,hls_ip_2023_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7k325t-ffg900-2,HLS_INPUT_CLOCK=100.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=6.092958,HLS_SYN_LAT=17,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=976,HLS_SYN_LUT=2849,HLS_VERSION=2023_2}" *)

module t64_nv12toCAG444_k8 (
        ap_clk,
        ap_rst_n,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        Yin_dout,
        Yin_empty_n,
        Yin_read,
        UVin_dout,
        UVin_empty_n,
        UVin_read,
        YUVout_din,
        YUVout_full_n,
        YUVout_write
);

parameter    ap_ST_fsm_state1 = 8'd1;
parameter    ap_ST_fsm_state2 = 8'd2;
parameter    ap_ST_fsm_state3 = 8'd4;
parameter    ap_ST_fsm_state4 = 8'd8;
parameter    ap_ST_fsm_state5 = 8'd16;
parameter    ap_ST_fsm_state6 = 8'd32;
parameter    ap_ST_fsm_state7 = 8'd64;
parameter    ap_ST_fsm_state8 = 8'd128;

input   ap_clk;
input   ap_rst_n;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [63:0] Yin_dout;
input   Yin_empty_n;
output   Yin_read;
input  [63:0] UVin_dout;
input   UVin_empty_n;
output   UVin_read;
output  [63:0] YUVout_din;
input   YUVout_full_n;
output   YUVout_write;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg Yin_read;
reg UVin_read;

 reg    ap_rst_n_inv;
(* fsm_encoding = "none" *) reg   [7:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    Yin_blk_n;
wire    ap_CS_fsm_state2;
wire    ap_CS_fsm_state3;
reg    UVin_blk_n;
reg    YUVout_blk_n;
wire    ap_CS_fsm_state5;
wire    ap_CS_fsm_state6;
wire    ap_CS_fsm_state7;
wire    ap_CS_fsm_state8;
reg   [63:0] Yin_read_reg_130;
reg   [63:0] UVin_read_reg_135;
wire   [127:0] Yin128_fu_80_p3;
reg   [127:0] Yin128_reg_140;
wire   [127:0] UVin128_fu_88_p3;
reg   [127:0] UVin128_reg_145;
wire   [63:0] trunc_ln30_fu_99_p1;
reg   [63:0] p_s_reg_155;
reg   [63:0] p_0_reg_160;
wire    grp_t64_nv12toCAG444_k8_Pipeline_VITIS_LOOP_17_1_fu_73_ap_start;
wire    grp_t64_nv12toCAG444_k8_Pipeline_VITIS_LOOP_17_1_fu_73_ap_done;
wire    grp_t64_nv12toCAG444_k8_Pipeline_VITIS_LOOP_17_1_fu_73_ap_idle;
wire    grp_t64_nv12toCAG444_k8_Pipeline_VITIS_LOOP_17_1_fu_73_ap_ready;
wire   [191:0] grp_t64_nv12toCAG444_k8_Pipeline_VITIS_LOOP_17_1_fu_73_YUVout192_out;
wire    grp_t64_nv12toCAG444_k8_Pipeline_VITIS_LOOP_17_1_fu_73_YUVout192_out_ap_vld;
reg    grp_t64_nv12toCAG444_k8_Pipeline_VITIS_LOOP_17_1_fu_73_ap_start_reg;
reg    ap_block_state3;
reg    ap_block_state3_ignore_call15;
wire    ap_CS_fsm_state4;
reg    ap_block_state2;
wire    regslice_forward_YUVout_U_apdone_blk;
reg    ap_block_state8;
reg   [7:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
reg    ap_ST_fsm_state4_blk;
reg    ap_ST_fsm_state5_blk;
reg    ap_ST_fsm_state6_blk;
reg    ap_ST_fsm_state7_blk;
reg    ap_ST_fsm_state8_blk;
wire    regslice_forward_Yin_U_apdone_blk;
wire   [63:0] Yin_dout_int_regslice;
wire    Yin_empty_n_int_regslice;
reg    Yin_read_int_regslice;
wire    regslice_forward_Yin_U_ack_in;
wire    regslice_forward_UVin_U_apdone_blk;
wire   [63:0] UVin_dout_int_regslice;
wire    UVin_empty_n_int_regslice;
reg    UVin_read_int_regslice;
wire    regslice_forward_UVin_U_ack_in;
reg   [63:0] YUVout_din_int_regslice;
reg    YUVout_write_int_regslice;
wire    YUVout_full_n_int_regslice;
wire    regslice_forward_YUVout_U_vld_out;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 8'd1;
#0 grp_t64_nv12toCAG444_k8_Pipeline_VITIS_LOOP_17_1_fu_73_ap_start_reg = 1'b0;
end

t64_nv12toCAG444_k8_t64_nv12toCAG444_k8_Pipeline_VITIS_LOOP_17_1 grp_t64_nv12toCAG444_k8_Pipeline_VITIS_LOOP_17_1_fu_73(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_t64_nv12toCAG444_k8_Pipeline_VITIS_LOOP_17_1_fu_73_ap_start),
    .ap_done(grp_t64_nv12toCAG444_k8_Pipeline_VITIS_LOOP_17_1_fu_73_ap_done),
    .ap_idle(grp_t64_nv12toCAG444_k8_Pipeline_VITIS_LOOP_17_1_fu_73_ap_idle),
    .ap_ready(grp_t64_nv12toCAG444_k8_Pipeline_VITIS_LOOP_17_1_fu_73_ap_ready),
    .UVin128(UVin128_reg_145),
    .Yin128(Yin128_reg_140),
    .YUVout192_out(grp_t64_nv12toCAG444_k8_Pipeline_VITIS_LOOP_17_1_fu_73_YUVout192_out),
    .YUVout192_out_ap_vld(grp_t64_nv12toCAG444_k8_Pipeline_VITIS_LOOP_17_1_fu_73_YUVout192_out_ap_vld)
);

t64_nv12toCAG444_k8_regslice_forward #(
    .DataWidth( 64 ))
regslice_forward_Yin_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(Yin_dout),
    .vld_in(Yin_empty_n),
    .ack_in(regslice_forward_Yin_U_ack_in),
    .data_out(Yin_dout_int_regslice),
    .vld_out(Yin_empty_n_int_regslice),
    .ack_out(Yin_read_int_regslice),
    .apdone_blk(regslice_forward_Yin_U_apdone_blk)
);

t64_nv12toCAG444_k8_regslice_forward #(
    .DataWidth( 64 ))
regslice_forward_UVin_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(UVin_dout),
    .vld_in(UVin_empty_n),
    .ack_in(regslice_forward_UVin_U_ack_in),
    .data_out(UVin_dout_int_regslice),
    .vld_out(UVin_empty_n_int_regslice),
    .ack_out(UVin_read_int_regslice),
    .apdone_blk(regslice_forward_UVin_U_apdone_blk)
);

t64_nv12toCAG444_k8_regslice_forward #(
    .DataWidth( 64 ))
regslice_forward_YUVout_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(YUVout_din_int_regslice),
    .vld_in(YUVout_write_int_regslice),
    .ack_in(YUVout_full_n_int_regslice),
    .data_out(YUVout_din),
    .vld_out(regslice_forward_YUVout_U_vld_out),
    .ack_out(YUVout_full_n),
    .apdone_blk(regslice_forward_YUVout_U_apdone_blk)
);

always @ (posedge ap_rst_n_inv or posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_rst_n_inv or posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_t64_nv12toCAG444_k8_Pipeline_VITIS_LOOP_17_1_fu_73_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state3) & (1'b0 == ap_block_state3_ignore_call15))) begin
            grp_t64_nv12toCAG444_k8_Pipeline_VITIS_LOOP_17_1_fu_73_ap_start_reg <= 1'b1;
        end else if ((grp_t64_nv12toCAG444_k8_Pipeline_VITIS_LOOP_17_1_fu_73_ap_ready == 1'b1)) begin
            grp_t64_nv12toCAG444_k8_Pipeline_VITIS_LOOP_17_1_fu_73_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        UVin128_reg_145 <= UVin128_fu_88_p3;
        Yin128_reg_140 <= Yin128_fu_80_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        UVin_read_reg_135 <= UVin_dout_int_regslice;
        Yin_read_reg_130 <= Yin_dout_int_regslice;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        p_0_reg_160 <= {{grp_t64_nv12toCAG444_k8_Pipeline_VITIS_LOOP_17_1_fu_73_YUVout192_out[191:128]}};
        p_s_reg_155 <= {{grp_t64_nv12toCAG444_k8_Pipeline_VITIS_LOOP_17_1_fu_73_YUVout192_out[127:64]}};
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2))) begin
        UVin_blk_n = UVin_empty_n_int_regslice;
    end else begin
        UVin_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((regslice_forward_UVin_U_ack_in == 1'b1) & (1'b1 == UVin_empty_n))) begin
        UVin_read = 1'b1;
    end else begin
        UVin_read = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_state3) & (1'b0 == ap_block_state3)) | ((1'b1 == ap_CS_fsm_state2) & (1'b0 == ap_block_state2)))) begin
        UVin_read_int_regslice = 1'b1;
    end else begin
        UVin_read_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5))) begin
        YUVout_blk_n = YUVout_full_n_int_regslice;
    end else begin
        YUVout_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == YUVout_full_n_int_regslice)) begin
        if ((1'b1 == ap_CS_fsm_state7)) begin
            YUVout_din_int_regslice = p_0_reg_160;
        end else if ((1'b1 == ap_CS_fsm_state6)) begin
            YUVout_din_int_regslice = p_s_reg_155;
        end else if ((1'b1 == ap_CS_fsm_state5)) begin
            YUVout_din_int_regslice = trunc_ln30_fu_99_p1;
        end else begin
            YUVout_din_int_regslice = 'bx;
        end
    end else begin
        YUVout_din_int_regslice = 'bx;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_state7) & (1'b1 == YUVout_full_n_int_regslice)) | ((1'b1 == ap_CS_fsm_state6) & (1'b1 == YUVout_full_n_int_regslice)) | ((1'b1 == ap_CS_fsm_state5) & (1'b1 == YUVout_full_n_int_regslice)))) begin
        YUVout_write_int_regslice = 1'b1;
    end else begin
        YUVout_write_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2))) begin
        Yin_blk_n = Yin_empty_n_int_regslice;
    end else begin
        Yin_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((regslice_forward_Yin_U_ack_in == 1'b1) & (1'b1 == Yin_empty_n))) begin
        Yin_read = 1'b1;
    end else begin
        Yin_read = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_state3) & (1'b0 == ap_block_state3)) | ((1'b1 == ap_CS_fsm_state2) & (1'b0 == ap_block_state2)))) begin
        Yin_read_int_regslice = 1'b1;
    end else begin
        Yin_read_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state2)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state3)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_t64_nv12toCAG444_k8_Pipeline_VITIS_LOOP_17_1_fu_73_ap_done == 1'b0)) begin
        ap_ST_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_fsm_state4_blk = 1'b0;
    end
end

always @ (*) begin
    if ((1'b0 == YUVout_full_n_int_regslice)) begin
        ap_ST_fsm_state5_blk = 1'b1;
    end else begin
        ap_ST_fsm_state5_blk = 1'b0;
    end
end

always @ (*) begin
    if ((1'b0 == YUVout_full_n_int_regslice)) begin
        ap_ST_fsm_state6_blk = 1'b1;
    end else begin
        ap_ST_fsm_state6_blk = 1'b0;
    end
end

always @ (*) begin
    if ((1'b0 == YUVout_full_n_int_regslice)) begin
        ap_ST_fsm_state7_blk = 1'b1;
    end else begin
        ap_ST_fsm_state7_blk = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state8)) begin
        ap_ST_fsm_state8_blk = 1'b1;
    end else begin
        ap_ST_fsm_state8_blk = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state8) & (1'b0 == ap_block_state8))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state8) & (1'b0 == ap_block_state8))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b1 == ap_CS_fsm_state2) & (1'b0 == ap_block_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((1'b1 == ap_CS_fsm_state3) & (1'b0 == ap_block_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            if (((grp_t64_nv12toCAG444_k8_Pipeline_VITIS_LOOP_17_1_fu_73_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state5 : begin
            if (((1'b1 == ap_CS_fsm_state5) & (1'b1 == YUVout_full_n_int_regslice))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        ap_ST_fsm_state6 : begin
            if (((1'b1 == ap_CS_fsm_state6) & (1'b1 == YUVout_full_n_int_regslice))) begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        ap_ST_fsm_state7 : begin
            if (((1'b1 == ap_CS_fsm_state7) & (1'b1 == YUVout_full_n_int_regslice))) begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end
        end
        ap_ST_fsm_state8 : begin
            if (((1'b1 == ap_CS_fsm_state8) & (1'b0 == ap_block_state8))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign UVin128_fu_88_p3 = {{UVin_dout_int_regslice}, {UVin_read_reg_135}};

assign YUVout_write = regslice_forward_YUVout_U_vld_out;

assign Yin128_fu_80_p3 = {{Yin_dout_int_regslice}, {Yin_read_reg_130}};

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

always @ (*) begin
    ap_block_state2 = ((1'b0 == UVin_empty_n_int_regslice) | (1'b0 == Yin_empty_n_int_regslice));
end

always @ (*) begin
    ap_block_state3 = ((1'b0 == UVin_empty_n_int_regslice) | (1'b0 == Yin_empty_n_int_regslice));
end

always @ (*) begin
    ap_block_state3_ignore_call15 = ((1'b0 == UVin_empty_n_int_regslice) | (1'b0 == Yin_empty_n_int_regslice));
end

always @ (*) begin
    ap_block_state8 = ((1'b0 == YUVout_full_n_int_regslice) | (regslice_forward_YUVout_U_apdone_blk == 1'b1));
end

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign grp_t64_nv12toCAG444_k8_Pipeline_VITIS_LOOP_17_1_fu_73_ap_start = grp_t64_nv12toCAG444_k8_Pipeline_VITIS_LOOP_17_1_fu_73_ap_start_reg;

assign trunc_ln30_fu_99_p1 = grp_t64_nv12toCAG444_k8_Pipeline_VITIS_LOOP_17_1_fu_73_YUVout192_out[63:0];

endmodule //t64_nv12toCAG444_k8
